# fly.toml app configuration file generated for iroha on 2023-07-03T16:59:18+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "iroha"
primary_region = "nrt"
console_command = "/rails/bin/rails console"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/iroha/public"
  url_prefix = "/"
